serviceAccount:
  # Annotations to add to the service account (like the ARN of the IRSA role)
  annotations: {}
controller:
  defaultImage: public.ecr.aws/karpenter/controller:v0.2.2@sha256:a601fb1d5c9462697ca9add59474462f89ebb605e1a18380168e9e308ca0dcab
# fill the variable below if you want to override the default image
#  repository:
#  tag:

nodeSelector: {}
tolerations: []
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64

---
