apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: karpenter-selfsigned-issuer
  namespace: karpenter
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: karpenter-serving-cert
  namespace: karpenter
spec:
  dnsNames:
  - karpenter-webhook-service.karpenter.svc
  - karpenter-webhook-service.karpenter.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: karpenter-selfsigned-issuer
  secretName: karpenter-webhook-server-cert # this secret will not be prefixed, since it's not managed by kustomize
