name: CI
on: [pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
     
    - name: CI - Verifications and Tests
      run: |
        make toolchain 
        echo "/usr/local/kubebuilder/bin" >> $GITHUB_PATH
        make ci
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Code Coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage.html
